
const KEY_DOWN = "keydown";
const KEY_UP = "keyup";
const ARROW_UP = "ArrowUp";
const ARROW_DOWN = "ArrowDown";
const ENTER = "Enter";

const DEBOUNCE_DELAY = 1000;

const NUM_SCHOOLS_PLACEHOLDER = 240;
const NUM_RATINGS_PLACEHOLDER = 34890;

export {
	KEY_DOWN,
	KEY_UP,
	ARROW_DOWN,
	ARROW_UP,
	ENTER,
	DEBOUNCE_DELAY,
	NUM_RATINGS_PLACEHOLDER,
	NUM_SCHOOLS_PLACEHOLDER
}