
const KEY_DOWN = "keydown";
const KEY_UP = "keyup";
const ARROW_UP = "ArrowUp";
const ARROW_DOWN = "ArrowDown";
const ENTER = "Enter";

const DEBOUNCE_DELAY = 500;

const NUM_SCHOOLS_PLACEHOLDER = 240;
const NUM_RATINGS_PLACEHOLDER = 34890;

const MAX_DEPARTMENTS = 8;
const MAX_DIFFICULTY_CLASSES = 10;
const MAX_BOOSTER_CLASSES = 10;

export {
	KEY_DOWN,
	KEY_UP,
	ARROW_DOWN,
	ARROW_UP,
	ENTER,
	DEBOUNCE_DELAY,
	NUM_RATINGS_PLACEHOLDER,
	NUM_SCHOOLS_PLACEHOLDER,
	MAX_BOOSTER_CLASSES,
	MAX_DEPARTMENTS,
	MAX_DIFFICULTY_CLASSES
}