
const KEY_DOWN = "keydown";
const KEY_UP = "keyup";
const ARROW_UP = "ArrowUp";
const ARROW_DOWN = "ArrowDown";
const ENTER = "Enter";

const DEBOUNCE_DELAY = 500;

const NUM_SCHOOLS_PLACEHOLDER = 240;
const NUM_RATINGS_PLACEHOLDER = 34890;

const MAX_DEPARTMENTS = 8;
const MAX_DIFFICULTY_CLASSES = 10;
const MAX_BOOSTER_CLASSES = 10;
const MAX_COMMENTS = 10;

const NUM_TEXTAREA_ROWS = 8;
const NUM_TEXTAREA_COLS = 80;

const LENGTH_TEACHER_NAME = 25;
const LENGTH_PRIMARY_TEXT = 350;
const LENGTH_SECONDARY_TEXT = 350;

const ALERT_TIME = 5000;


export {
	KEY_DOWN,
	KEY_UP,
	ARROW_DOWN,
	ARROW_UP,
	ENTER,
	DEBOUNCE_DELAY,
	NUM_RATINGS_PLACEHOLDER,
	NUM_SCHOOLS_PLACEHOLDER,
	MAX_BOOSTER_CLASSES,
	MAX_DEPARTMENTS,
	MAX_DIFFICULTY_CLASSES,
	MAX_COMMENTS,
	NUM_TEXTAREA_ROWS,
	NUM_TEXTAREA_COLS,
	LENGTH_PRIMARY_TEXT,
	LENGTH_SECONDARY_TEXT,
	LENGTH_TEACHER_NAME,
	ALERT_TIME
}