-- CreateEnum
CREATE TYPE "TAG" AS ENUM ('TEST_HEAVY', 'ASSIGNMENT_HEAVY', 'LECTURES_RECORDED', 'REQUIRED', 'AVOID', 'RECOMMENDED', 'THEORY_HEAVY', 'READING_HEAVY', 'GROUPWORK_HEAVY', 'PARTICIPATION_MATTERS');

-- AlterTable
ALTER TABLE "comments" ADD COLUMN     "overall_rating" DOUBLE PRECISION;

-- DropEnum
DROP TYPE "COMMENT_INTERACTION";
