-- AlterTable
ALTER TABLE "classes" ALTER COLUMN "avg_difficulty" SET DEFAULT 0,
ALTER COLUMN "avg_difficulty" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "avg_grade" SET DEFAULT 0,
ALTER COLUMN "avg_grade" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "avg_boost" SET DEFAULT 0,
ALTER COLUMN "avg_boost" SET DATA TYPE DOUBLE PRECISION;
